name: "e2e: noscience, self-hosted"

on:
  repository_dispatch:
    types: [e2e]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: get_branch
      run: |
        BRANCH="${{ github.event.client_payload.branch }}"
        echo "Branche reçue : $BRANCH"

        # Vérifier si la branche existe sur le dépôt
        if git ls-remote --heads origin $BRANCH | grep $BRANCH; then
          echo "Branche valide : $BRANCH"
        else
          echo "Erreur : La branche n'existe pas !" >&2
          exit 1
        fi
    - name: checkout_branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.branch }}
    - name: build
      run: |
        echo "Branch received: ${{ github.event.client_payload.branch }}"
        if [ "${{ github.event.client_payload.build }}" == "true" ]; then
          echo "build success for image $image"
        else
          echo "build failed for image $image"
          exit 1
        fi
    - name: e2e
      run: |
        if [ "${{ github.event.client_payload.e2e }}" == "true" ]; then

          echo "Succeed to run e2e tests on cluster $cluster"
        else
          echo "Failed to run e2e tests on cluster $cluster"
          exit 1
        fi
